FROM golang
MAINTAINER YangJunhai <yangjunhai@xindong.com>
COPY . /go/src/github.com/pirateXD/registrator
RUN go build -ldflags "-X main.Version=$(cat VERSION)" -o /bin/registrator
ENTRYPOINT ["/bin/registrator"]
CMD ["--help"]